// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "serverless-node",
    "version": "1"
  },
  "paths": {
    "/test": {
      "get": {
        "summary": "test",
        "description": "",
        "tags": [
          "TEST"
        ],
        "operationId": "test.get./test",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};